---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 4096

provisioner:
  name: chef_zero
  config_rb:
    environment: dev

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[forensic_reporter::default]
    attributes:
      forensic_reporter:
        env:
          LOAD_THRESHOLD: '0.00'
          REPORT_EMAIL: vagrant
          REPORT_DELAY_SECS: 0
