#!/usr/bin/env bash

source /etc/forensic_reporter.conf

if [ -d ${OUTPUT_DIR} ]; then
  rm -rf ${OUTPUT_DIR}
fi

while true; do
  loadavg=$(cat /proc/loadavg | awk '{print $3}')
  high_load=$(echo "${loadavg} >= ${LOAD_THRESHOLD}" | bc)

  if [[ $high_load == 1 ]]; then
    if [ ! -d ${OUTPUT_DIR} ]; then
      mkdir -p ${OUTPUT_DIR}
    fi

    # Datestamp
    datestamp=$(date "+%F-%H-%M-%S-%Z")
    output_file="${OUTPUT_DIR}/${datestamp}"

    # Load Average
    cat /proc/loadavg >> "${output_file}"

    # Free Memory
    free >> "${output_file}"

    echo >> "${output_file}"

    # Full process table in tree format
    ps axjfww >> "${output_file}"
    echo >> "${output_file}"
    ps auxww >> "${output_file}"
    
    oldest_file=$(ls -1tr ${OUTPUT_DIR}/* | head -n 1)
    oldest_file_ctime=$(stat -c %Y "${oldest_file}")
    oldest_file_age=$(($(date +%s) - $oldest_file_ctime))

    # Send the email
    if [ $oldest_file_age -gt $REPORT_DELAY_SECS ]; then
      echo "loadavg: $(cat /proc/loadavg)" \
        | mail \
          -s "Overage report for $(hostname -s)" \
          -A $(find ${OUTPUT_DIR} -type f) \
          root
      # Delete the reports we've already emailed
      rm -f ${OUTPUT_DIR}/*
    fi
  elif [ -d ${OUTPUT_DIR} ]; then
    # Delete the report directory if the problem fixes itself
    rm -rf ${OUTPUT_DIR}
  fi
  sleep 15
done
